#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["test/WazenAdmin.API.IntegrationTests/WazenAdmin.API.IntegrationTests.csproj", "test/WazenAdmin.API.IntegrationTests/"]
COPY ["src/Infrastructure/WazenAdmin.Persistence/WazenAdmin.Persistence.csproj", "src/Infrastructure/WazenAdmin.Persistence/"]
COPY ["src/Core/WazenAdmin.Application/WazenAdmin.Application.csproj", "src/Core/WazenAdmin.Application/"]
COPY ["src/Core/WazenAdmin.Domain/WazenAdmin.Domain.csproj", "src/Core/WazenAdmin.Domain/"]
COPY ["src/API/WazenAdmin.Api/WazenAdmin.Api.csproj", "src/API/WazenAdmin.Api/"]
COPY ["src/Infrastructure/WazenAdmin.Infrastructure/WazenAdmin.Infrastructure.csproj", "src/Infrastructure/WazenAdmin.Infrastructure/"]
COPY ["src/Infrastructure/WazenAdmin.Identity/WazenAdmin.Identity.csproj", "src/Infrastructure/WazenAdmin.Identity/"]
RUN dotnet restore "test/WazenAdmin.API.IntegrationTests/WazenAdmin.API.IntegrationTests.csproj"
COPY . .
WORKDIR "/src/test/WazenAdmin.API.IntegrationTests"
RUN dotnet build "WazenAdmin.API.IntegrationTests.csproj" -c Release -o /app/build

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /wait
RUN chmod +x /wait

# Wait for sql server and then migrate the db and run tests
CMD /wait && dotnet ef database update --context MyDbContext && dotnet test --no-build

FROM build AS publish
RUN dotnet publish "WazenAdmin.API.IntegrationTests.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WazenAdmin.API.IntegrationTests.dll"]