kind: Deployment
apiVersion: apps/v1
metadata:
  name: wazen-admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: admin 
    spec:
      containers:
        - name: admin
          image: wazen.azurecr.io/wazenadmin:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env:
            - name: ConnectionString__ApplicationConnectionString
              value: "Server=20.233.38.75,1802;Database=WazenAdmin;User ID=wazenadmin;Password=wazenadmin@123;Trusted_Connection=True;TrustServerCertificate=False;Encrypt=True;MultiSubnetFailover=True"
            - name: ConnectionString__IdentityConnectionString
              value: "Server=20.233.38.75,1802;Database=WazenAdmin;User ID=wazenadmin;Password=wazenadmin@123;Trusted_Connection=True;TrustServerCertificate=False;Encrypt=True;MultiSubnetFailover=True"
            - name: ConnectionString__HealthCheckConnectionString
              value: "Server=20.233.38.75,1802;Database=WazenAdmin;User ID=wazenadmin;Password=wazenadmin@123;Trusted_Connection=True;TrustServerCertificate=False;Encrypt=True;MultiSubnetFailover=True"
            - name: ConnectionString__KeyValue
              value: "MAKV2SPBNI99212"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      imagePullSecrets:
        - name: wazen-acr-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
